feat: publish button changes
openedx/frontend-app-library-authoring pull request #302
Opened 2023-09-14 09:34 UTC by rayzhou-bit

2023-09-14 13:19 UTC, KristinAoki approved these changes

2023-09-14 13:19 UTC, KristinAoki requested changes
Code coverage needs to increase before this is merged in

2023-09-21 16:21 UTC, KristinAoki reviewed
Tests look good. There is one case where I am not sure if the publish button should or shouldn't be enabled. Case:

1. User adds a new block (publish button should be enabled)
2. User deletes newly created block which returns library to previously published state.

In the step two should the publish button be disabled? Currently it is still enabled and says that the library is in draft form.

2023-09-21 17:24 UTC, rayzhou-bit commented
@KristinAoki This behavior makes sense to me, but it is not what we see with course-authoring right now.

2023-09-21 17:25 UTC, KristinAoki approved these changes

2023-09-21 17:40 UTC, merged