Add a tutor plugin to easily run this on a devstack
openedx/frontend-app-library-authoring pull request #50
Opened 2022-07-05 04:55 UTC by bradenmacdonald

It's a bit tricky to get this working on a Tutor-based devstack, but this plugin should make it easy!

Known issues:
* Right now it's still not working end-to-end because the CMS/LMS tries to download files from `studio.local.overhang.io:8001` which is not accessible on that port from within the CMS container. Probably need to change the Blockstore config.

2022-07-05 04:55 UTC, openedx-webhooks commented
Thanks for the pull request, @bradenmacdonald!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-07-20 19:52 UTC, natabene commented
@bradenmacdonald Thank you for your contribution. Please let me know once this is ready for our review.

2022-07-20 23:53 UTC, bradenmacdonald commented
@natabene It's ready now. There is an error in the CI build but it's not related to this. I'm not sure if this repo has a maintainer at the moment? Because the build is failing because nobody is updating the dependencies of this repo and/or several related repos like @edx/frontend-component-footer

2022-08-15 13:37 UTC, connorhaugh commented
Braden, I gave this a test (for local dev development) on my local tutor and it seems to work. I'll give a thumb here when we resolve the unrelated CI issues and see this PR merged.

2022-08-15 16:01 UTC, connorhaugh commented
@bradenmacdonald a rebase off master should fix the CI issues.

2022-08-15 18:24 UTC, bradenmacdonald commented
@connorhaugh Thanks!! Yep, that did it.

2022-09-09 13:11 UTC, brian-smith-tcril commented
I tested this locally.

## tl;dr
I needed to run `pip install -e git+https://github.com/open-craft/frontend-app-library-authoring.git@tutor-devstack-plugin#egg=tutor_contrib_library_authoring_mfe\&subdirectory=tutor-contrib-library-authoring-mfe` for this to install correctly.

## Questions
* Is escaping the `&` is required on all platforms?
* What are the conventions around using `contrib` in tutor plugin names?
  * Should `tutor-contrib-library-authoring-mfe` be updated to be `tutor-library-authoring-mfe` in `setup.py` before this gets merged?

## Play by play

First issue I encountered was related to the line
```
pip install -e git+https://github.com/openedx/frontend-app-library-authoring.git#egg=tutor_library_authoring_mfe&subdirectory=tutor-contrib-library-authoring-mfe
```
which, for testing purposes, i updated to be
```
pip install -e git+https://github.com/open-craft/frontend-app-library-authoring.git@tutor-devstack-plugin#egg=tutor_library_authoring_mfe&subdirectory=tutor-contrib-library-authoring-mfe
```
when running it, I encountered an error
```
ERROR: tutor_library_authoring_mfe from git+https://github.com/open-craft/frontend-app-library-authoring.git@tutor-devstack-plugin#egg=tutor_library_authoring_mfe (from -r /tmp/pipenv-ikn3q7vk-requirements/pipenv-a7yegfe3-requirement.txt (line 1)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```
which I resolved by escaping the `&` by using `\&`
```
pip install -e git+https://github.com/open-craft/frontend-app-library-authoring.git@tutor-devstack-plugin#egg=tutor_library_authoring_mfe\&subdirectory=tutor-contrib-library-authoring-mfe
```
when running that, I encountered another error
```
  WARNING: Generating metadata for package tutor_library_authoring_mfe produced metadata for project name tutor-contrib-library-authoring-mfe. Fix your #egg=tutor_library_authoring_mfe fragments.
ERROR: Could not find a version that satisfies the requirement tutor-library-authoring-mfe (unavailable) (from versions: none)
ERROR: No matching distribution found for tutor-library-authoring-mfe (unavailable)
```
I'm not sure what the conventions around using `contrib` are, but that seemed to be causing the issue.

I pushed the branch to my fork, and made a commit (https://github.com/brian-smith-tcril/frontend-app-library-authoring/commit/49827046f6869f95b29a3f3b1e220e189844c7fd) updating `setup.py` to use `tutor-library-authoring-mfe` as the name instead of `tutor-contrib-library-authoring-mfe`

installing this using
```
pip install -e git+https://github.com/brian-smith-tcril/frontend-app-library-authoring.git@tutor-plugin#egg=tutor_library_authoring_mfe\&subdirectory=tutor-contrib-library-authoring-mfe
```
worked as expected, at which point I uninstalled and decided to try
```
pip install -e git+https://github.com/open-craft/frontend-app-library-authoring.git@tutor-devstack-plugin#egg=tutor_contrib_library_authoring_mfe\&subdirectory=tutor-contrib-library-authoring-mfe
```
which worked as expected

2022-09-09 13:11 UTC, brian-smith-tcril commented
I tested this locally.

## tl;dr
I needed to run `pip install -e git+https://github.com/open-craft/frontend-app-library-authoring.git@tutor-devstack-plugin#egg=tutor_contrib_library_authoring_mfe\&subdirectory=tutor-contrib-library-authoring-mfe` for this to install correctly.

## Questions
* Is escaping the `&` is required on all platforms?
* What are the conventions around using `contrib` in tutor plugin names?
  * Should `tutor-contrib-library-authoring-mfe` be updated to be `tutor-library-authoring-mfe` in `setup.py` before this gets merged?

## Play by play

First issue I encountered was related to the line
```
pip install -e git+https://github.com/openedx/frontend-app-library-authoring.git#egg=tutor_library_authoring_mfe&subdirectory=tutor-contrib-library-authoring-mfe
```
which, for testing purposes, i updated to be
```
pip install -e git+https://github.com/open-craft/frontend-app-library-authoring.git@tutor-devstack-plugin#egg=tutor_library_authoring_mfe&subdirectory=tutor-contrib-library-authoring-mfe
```
when running it, I encountered an error
```
ERROR: tutor_library_authoring_mfe from git+https://github.com/open-craft/frontend-app-library-authoring.git@tutor-devstack-plugin#egg=tutor_library_authoring_mfe (from -r /tmp/pipenv-ikn3q7vk-requirements/pipenv-a7yegfe3-requirement.txt (line 1)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```
which I resolved by escaping the `&` by using `\&`
```
pip install -e git+https://github.com/open-craft/frontend-app-library-authoring.git@tutor-devstack-plugin#egg=tutor_library_authoring_mfe\&subdirectory=tutor-contrib-library-authoring-mfe
```
when running that, I encountered another error
```
  WARNING: Generating metadata for package tutor_library_authoring_mfe produced metadata for project name tutor-contrib-library-authoring-mfe. Fix your #egg=tutor_library_authoring_mfe fragments.
ERROR: Could not find a version that satisfies the requirement tutor-library-authoring-mfe (unavailable) (from versions: none)
ERROR: No matching distribution found for tutor-library-authoring-mfe (unavailable)
```
I'm not sure what the conventions around using `contrib` are, but that seemed to be causing the issue.

I pushed the branch to my fork, and made a commit (https://github.com/brian-smith-tcril/frontend-app-library-authoring/commit/49827046f6869f95b29a3f3b1e220e189844c7fd) updating `setup.py` to use `tutor-library-authoring-mfe` as the name instead of `tutor-contrib-library-authoring-mfe`

installing this using
```
pip install -e git+https://github.com/brian-smith-tcril/frontend-app-library-authoring.git@tutor-plugin#egg=tutor_library_authoring_mfe\&subdirectory=tutor-contrib-library-authoring-mfe
```
worked as expected, at which point I uninstalled and decided to try
```
pip install -e git+https://github.com/open-craft/frontend-app-library-authoring.git@tutor-devstack-plugin#egg=tutor_contrib_library_authoring_mfe\&subdirectory=tutor-contrib-library-authoring-mfe
```
which worked as expected

2022-09-09 14:02 UTC, brian-smith-tcril commented
After getting it running, I tried creating a content library and adding some components. Creating the library worked as expected, but every component is failing to load with the error: `Cannot GET /library_authoring/xblock-bootstrap.html`

I'm thinking this may be related to the change from `library_authoring` to `library-authoring` in this commit https://github.com/openedx/frontend-app-library-authoring/commit/d719044cb8f570ba719736aac76fef914e5b4b6c

2022-09-09 15:07 UTC, brian-smith-tcril requested changes
Overall this is really great! I'm super excited to see MFEs working as tutor plugins!

The big one here is the change in `plugin.py`, without that this just doesn't work.

I'm not sure about escaping the `&` in the readme, but running the command didn't work for me without it. I'm also not sure what to do about the `tutor_contrib_library_authoring_mfe` vs `tutor_library_authoring_mfe` thing, so it'd be helpful to get some outside input on that.

Looking forward to seeing what we can do to get this merged in!

2022-09-09 15:07 UTC, brian-smith-tcril commented on tutor-contrib-library-authoring-mfe/README.rst
> +1. Install this plugin: ``pip install -e git+https://github.com/openedx/frontend-app-library-authoring.git#egg=tutor_library_authoring_mfe&subdirectory=tutor-contrib-library-authoring-mfe``
```suggestion
1. Install this plugin: ``pip install -e git+https://github.com/openedx/frontend-app-library-authoring.git#egg=tutor_library_authoring_mfe\&subdirectory=tutor-contrib-library-authoring-mfe``
```
i ran into issues with the `&` not being escaped when running this locally

2022-09-09 15:07 UTC, brian-smith-tcril commented on tutor-contrib-library-authoring-mfe/tutor_library_authoring_mfe/plugin.py
> +            "SECURE_ORIGIN_XBLOCK_BOOTSTRAP_HTML_URL": "/library_authoring/xblock-bootstrap.html",
```suggestion
            "SECURE_ORIGIN_XBLOCK_BOOTSTRAP_HTML_URL": "/library-authoring/xblock-bootstrap.html",
```
tested this change on my fork and it resolved the `Cannot GET /library_authoring/xblock-bootstrap.html` error I encountered.

2022-09-09 15:22 UTC, arbrandes commented
Thanks for the in-depth review, @brian-smith-tcril!  From where I stand those are all great catches, though I'll let @bradenmacdonald weigh in and/or pull in your changes before we merge.

Also,

> I'm not sure what the conventions around using `contrib` are

There's some prior art by our colleague @kdmccormick: 

https://github.com/openedx/tutor-contrib-coursegraph

Which is to say, I'd try to fix it in the _other_ direction, if possible.  (In other words, getting the rid of the error when the package is prefixed with `tutor-contrib`.)

2022-09-09 15:52 UTC, kdmccormick commented
I'm excited about this plugin @bradenmacdonald, and thanks for working through that @brian-smith-tcril. 

I agree that the Python distribution name (the thing defined in `setup.py`) should be **tutor-contrib-library-authoring-mfe**. That way, if this is ever pushed to PyPI, it would be installed as `pip install tutor-contrib-library-authoring-mfe`, clarifying that it's a contributor plugin, not an official one.

The Python package name is good to remain as `tutor_library_authoring_mfe`. That'll ensure that the plugin can be enabled via `tutor enable library_authoring_mfe` instead of the awkward `tutor enable contrib_library_authoring_mfe`.

(the docs on all of this ^ aren't great yet, but they're deductible by reverse engineering https://github.com/overhangio/cookiecutter-tutor-plugin)

Some other notes:

* The `#egg=` should match the Python distribution name, not the Python package name. That is, it should be `#egg=tutor-contrib-library-authoring-mfe`, not `#egg=tutor_library_authoring_mfe`. I think it is working somewhat by coincidence currently because pip is willing to silently translate the underscores into hyphens.
* Instead of escaping the `&`, we could wrap the entire `git+https://...` thing in single quotes. That way, bash won't treat `&` as a special character.

2022-09-09 18:03 UTC, bradenmacdonald commented
Thanks for the review @brian-smith-tcril ! I've pushed bd5f2318687c9ad57f9186e189ecd491cc12989d to make those fixes. Would you mind checking if that did it?

> What are the conventions around using contrib in tutor plugin names?

Using `contrib` is required - Regis has asked that any plugins that aren't created by him, i.e. any unofficial plugins, use `contrib` in the name to clearly distinguish them from plugins supported by overhang.io.

2022-09-09 21:09 UTC, brian-smith-tcril approved these changes
Perfect!

I can verify this worked locally for me when I followed the instructions in `tutor-contrib-library-authoring-mfe/README.rst` when changing the install step to
```
pip install -e 'git+https://github.com/open-craft/frontend-app-library-authoring.git@tutor-devstack-plugin#egg=tutor-contrib-library-authoring-mfe&subdirectory=tutor-contrib-library-authoring-mfe'
```
I can verify again using the actual line from the README after this is merged.

2022-09-27 17:13 UTC, bradenmacdonald commented
@brian-smith-tcril @arbrandes Can we merge this now?

2022-10-17 19:51 UTC, merged

2022-10-17 19:51 UTC, openedx-webhooks commented
@bradenmacdonald 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-library-authoring&entry.867055334=https://github.com/openedx/frontend-app-library-authoring/pull/50&entry.1484655318=https://github.com/bradenmacdonald&entry.752974735=2022-07-05+04:55&entry.1917517419=2022-10-17+19:51&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->

2022-10-17 19:51 UTC, arbrandes commented
Let's merge this!  Apologies for the delay, @bradenmacdonald, and thanks for the contrib!